services:
  ci-runner:
    image: docker:24.0.7-dind  # ✅ Alpine-based image with apk
    container_name: flask-ci
    ports:
      - "5050:5050"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app/gan_shmuel
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=testing
    command: >
      sh -c "
      apk add --no-cache python3 py3-pip git &&
      git clone --branch test_compose --single-branch https://github.com/ShobashAndi/gan_shmuel /app/gan_shmuel &&
      cd /app/gan_shmuel/devops/ci &&
      python3 -m venv venv &&
      source venv/bin/activate &&
      pip install -r requirements.txt &&
      python3 webhook_server.py"