FROM python:3.13-slim
WORKDIR /app
EXPOSE 8501
COPY requirements2.txt .
RUN apt-get update && apt-get install -y \
    build-essential \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install --no-cache-dir -r requirements2.txt \
    && apt-get purge build-essential -y
COPY app/frontend.py .

CMD ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
