# Use Node.js LTS image
FROM node:18-alpine AS build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY app/frontend/package.json app/frontend/package-lock.json ./

# Install dependencies
RUN npm install --omit=dev

# Copy the rest of the app
COPY app/frontend/. .

# Build the app
RUN npm run build

# Use a lightweight web server for production
FROM nginx:alpine AS production

# Remove default Nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Copy our custom Nginx config
COPY nginx.conf /etc/nginx/conf.d/

# Set working directory in Nginx
WORKDIR /usr/share/nginx/html

# Copy built React app from the previous stage
COPY --from=build /app/dist .

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]